= Стандарт предприятия (БГУИР 2017)
Nadeŭka <nadevko@riseup.net>
v2017, 2024-02-23
:toc:

== 1 ОРГАНИЗАЦИЯ ДИПЛОМНОГО ПРОЕКТИРОВАНИЯ

=== 1.1 Общие положения

==== 1.1.1

Дипломный проект (работа) является выпускной квалификационной работой,
представляющей собой законченную самостоятельную научно-исследовательскую,
конструкторскую, производственно-технологическую, инженерно-экономическую или
организационно-управленческую разработку студента-дипломника, позволяющую
определить его теоретическую и практическую готовность к выполнению
социально-профессиональных задач по специальности (специализации).

==== 1.1.2

Содержанием дипломного проекта являются проектирование и конструирование изделия
в целом или его функционально законченной части, разработка технологического
процесса производства, создание аппаратно-программных средств, нахождение
инженерно-экономического и управленческого решения по повышению эффективности
производства.

==== 1.1.3

Содержанием дипломной работы являются научные и экспериментальные исследования
по одному из новых вопросов в области создания перспективных технических систем,
технологических процессов и производств, их информационное, алгоритмическое и
программное обеспечение; поиск инженерно-экономических и управленческих решений,
повышающих эффективность производства.

==== 1.1.4

Тематика дипломных проектов и работ ежегодно разрабатывается профилирующими
кафедрами с учетом специальности студентов и должна быть связана с решением
конкретных задач предприятий и организаций, на которые распределены студенты
(курсанты), или с тематикой НИР, выполняемых в университете и других
учреждениях. Темы дипломных проектов (работ) в зависимости от объема и сложности
решаемых задач могут выполняться как индивидуально (одним студентом
(курсантом)), так и коллективно, если для выполнения проекта (работы)
привлекается несколько студентов (курсантов). Причем для каждого студента
(курсанта) определяется конкретный раздел коллективно выполняемого проекта
(работы). В этом случае название темы должно состоять из двух частей: названия
коллективно выполняемой темы и названия разрабатываемой студентом (курсантом)
подтемы (раздела). Между названиями ставится точка.

==== 1.1.5

По каждой теме дипломного проекта (работы) кафедра определяет руководителя.
Руководителями могут быть лица из числа профессорско-преподавательского состава,
а также научные сотрудники и высококвалифицированные специалисты университета и
других учреждений и предприятий. В случае необходимости и по согласованию с
руководителем дипломного проекта (дипломной работы) выпускающей кафедре
предоставляется право приглашать консультантов по отдельным узконаправленным
разделам дипломного проекта (дипломной работы).

==== 1.1.6

Перечень тем дипломных проектов (работ), одобренных на заседании кафедры,
сообщают студентам (курсантам) не позднее чем за четыре недели до начала
преддипломной практики. Студентам (курсантам) предоставляется право выбора темы
дипломного проекта (работы). Студент (курсант) может предложить и свою тему с
обязательным письменным обоснованием целесообразности ее разработки.
Определившись с темой, студент (курсант) обязан не позднее чем за три недели до
начала преддипломной практики подать заявление на имя заведующего кафедрой с
просьбой утвердить тему и руководителя дипломного проекта (работы). Заявление
заполняется с помощью принтера или печатными прописными буквами от руки. Пример
оформления заявления приведен в приложении А. Студент (курсант) имеет право в
течение первой недели преддипломной практики после изучения задания по
дипломному проекту (работе) и с согласия руководителя ходатайствовать перед
кафедрой о внесении изменений в первоначальное название темы.

==== 1.1.7

Темы дипломных проектов (работ), их руководители, а также консультанты от
профилирующих кафедр по представлению деканов факультетов утверждаются приказом
ректора не позднее чем через 10 дней после начала преддипломной практики. Если в
дальнейшем по уважительной причине (документально подтвержденной) необходимо
изменить или уточнить тему дипломного проекта (работы), то декан факультета по
представлению кафедры возбуждает ходатайство о внесении соответствующих
изменений в приказ ректора. Однако такие изменения возможны только до окончания
срока преддипломной практики.

==== 1.1.8

Направление на преддипломную практику студент (курсант) получает в соответствии
с выбранной темой дипломного проекта (работы). Преддипломная практика проводится
индивидуально в организации любой формы собственности, в ее структурном
подразделении, соответствующем профилю профессиональной подготовки студента
(курсанта). Для руководства практикой назначается руководитель от организации
(обычно ведущий специалист – руководитель дипломного проекта) и руководитель от
выпускающей кафедры (обычно консультант по дипломному проекту). Студенты заочной
и дистанционной форм обучения преддипломную практику проходят в организациях по
профилю специальности (обычно по месту работы) или в БГУИР.

==== 1.1.9

Во время преддипломной практики студент (курсант) в соответствии с темой
дипломного проекта (работы) обязан изучить техническую документацию, патентные и
литературные источники, аналоги планируемых разработок; собрать и
систематизировать информацию, необходимую для решения технических,
экономических, управленческих и других специфических задач дипломного проекта
(работы), а также для разработки мероприятий, обеспечивающих безопасность труда
или экологическую безопасность, или энерго- и ресурсосбережение.
Целесообразность введения данного раздела в дипломный проект определяется
профилирующей кафедрой.

==== 1.1.10

В течение первой недели преддипломной практики после уточнения студентом
(курсантом) дипломной темы руководитель выдает студенту (курсанту) задание по
дипломному проекту (работе), определяет содержание и объем разделов проекта
(работы), а также составляет календарный план работы. Индивидуальные задания по
вопросам экономики и организации производства студент-дипломник (курсант)
получает от преподавателей-консультантов кафедр экономического профиля.
Индивидуальные задания по вопросу охраны труда, или экологической безопасности,
или энерго- и ресурсосбережения студент-дипломник (курсант) получает от
преподавателя-консультанта профилирующей кафедры. Студенты-дипломники
специальности 1-28 01 01 «Экономика электронного бизнеса» индивидуальные задания
по конструкторско-технологической части получают на кафедре проектирования
информационно-компьютерных систем (ПИКС). Задание в двух экземплярах в
соответствии с требованиями, изложенными в пункте 1.2.9, утверждается заведующим
выпускающей кафедрой не позднее срока окончания практики. Пример оформления
задания показан в приложении Б (сроки выполнения этапов указаны условно). Первый
экземпляр задания хранится у студента (курсанта) и затем подшивается в
пояснительную записку, а второй экземпляр и заявление студента (курсанта) об
утверждении темы и руководителя хранятся на кафедре в соответствии с
номенклатурой дел. В течение первой недели преддипломной практики руководители
дипломных проектов (работ) от сторонних организаций заключают договор подряда на
выполнение педагогической работы на условиях почасовой оплаты труда по нормам,
установленным в университете.

=== 1.2 Содержание частей дипломного проекта (работы)

==== 1.2.1

Дипломный проект (дипломная работа) должен состоять из графической части
(чертежи, графики, схемы, диаграммы, таблицы, рисунки и другой иллюстративный
материал) и расчетно-пояснительной записки, выполненных в соответствии с
требованиями стандартов Единой системы конструкторской, технологической и
программной документации (ЕСКД, ЕСТД и ЕСПД) и наглядно представляющих
завершенную работу и полученные результаты. Графическая часть дипломного проекта
(работы) должна быть представлена комплектом конструкторских, технологических,
программных и других документов на листах формата А1. Разрешается выбирать
форматы А2, А3 и А4, которые должны быть размещены на общем листе формата А1.
Общее количество листов графического материала (минимум шесть листов формата А1)
определяет руководитель в зависимости от темы дипломного проекта (работы). Объем
пояснительной записки, как правило, должен составлять 60–80 страниц печатного
текста, без учета приложений справочного или информационного характера.
Выпускающие кафедры разрабатывают и обеспечивают студентов (курсантов)
методическими указаниями по подготовке, оформлению и защите дипломных проектов
(работ) с учетом специфики специальности.

==== 1.2.2

Конструкторские документы выполняются с соблюдением требований ГОСТ 2.605–68 и
ГОСТ 2.120–73. Чертежи деталей машиностроения должны соответствовать техническим
требованиям СТБ 1014–95, чертежи сборочных единиц – СТБ 1022–96. Схемы
разрабатывают в соответствии с ГОСТ 2.701–2008. Могут использоваться другие виды
и типы схем, кроме тех, которые установлены указанным ГОСТом. В таких случаях
номенклатуру, наименования и коды этих видов и типов устанавливает выпускающая
кафедра. Технологическую документацию выполняют с соблюдением требований ГОСТ
3.1102–81, 3.1104–81, 3.1103–2008, 3.1109–82, 3.1201–85. Программные продукты
выполняют по ГОСТ 19.701–90. Оформление плакатов должно соответствовать
требованиям ГОСТ 2.605–68. Правила оформления графического материала, наиболее
часто разрабатываемого в дипломных проектах (работах), изложены в разделе 3.

==== 1.2.3

Каждый документ графической части дипломного проекта (работы) должен иметь
обозначение (шифр), которое включает в себя четырехбуквенный код университета
ГУИР; децимальный номер по классификатору ЕСКД ХХХХХХ; порядковый номер
графического материала; вид и тип документа.

==== 1.2.4

Пояснительную записку выполняют на листах формата А4 с применением печатающих и
графических устройств ПЭВМ. Разрешается исключать рамки и элементы оформления
листов пояснительной записки по ЕСКД. Пояснительная записка оформляется в
соответствии с требованиями ГОСТ 2.004–88, 2.105–95, 2.106–96, 7.1–2003.
Требования и правила составления пояснительной записки изложены в разделе 2.
Пояснительная записка должна быть переплетена (закреплена в твердой обложке) или
помещена в стандартную папку для дипломного проекта (работы). Общее количество
листов пояснительной записки без учета приложений справочного или
информационного характера, как правило, составляет 60–80 страниц печатного
текста, в том числе страниц по разделу технико-экономического обоснования – не
более 18 % от общего объема записки, по разделу охраны труда или экологической
безопасности, или по энерго- и ресурсосбережению – не более 5–7 % от общего
объема записки. По согласованию с выпускающей кафедрой пояснительную записку и
графический материал разрешается выполнять рукописным способом. В этом случае
общее количество листов пояснительной записки без приложений должно составлять
приблизительно 105 страниц.

==== 1.2.5

Пояснительная записка должна содержать:

* титульный лист;
* реферат;
* задание по дипломному проекту (работе);
* содержание;
* перечень условных обозначений, символов и терминов (если в этом есть
  необходимость);
* введение (предисловие);
* основной текст: разделы, представляющие обзор источников литературы по теме;
  используемые методы и (или) методики; собственные теоретические и
  экспериментальные исследования; результаты расчетов и проектирования; описание
  алгоритмов и другие разделы, определенные заданием. Для
  инженерно-экономических специальностей основной текст определяется выпускающей
  кафедрой;
* технико-экономическое обоснование (экономический раздел) принятых решений,
  определение экономической эффективности от внедрения полученных результатов.
  Для инженерно-экономических специальностей вместо экономического раздела
  выполняется конструкторско-технологический раздел;
* раздел охраны труда или экологической безопасности, или энерго- и
  ресурсосбережения (указать конкретное наименование раздела);
* заключение;
* список использованных источников;
* приложения (при необходимости);
* спецификация (перечень элементов);
* ведомость документов.

Указанную последовательность рекомендуется принять за порядок размещения
элементов и частей пояснительной записки.

==== 1.2.6

Пояснительная записка начинается с титульного листа. Образец титульного листа
выдается кафедрой и выполняется только с применением печатающего устройства
(приложение В). Наименование кафедры и факультета следует писать без сокращений.
Наименование темы проекта (работы) пишут прописными буквами. Наименование должно
в точности соответствовать названию, утвержденному приказом ректора по
университету. Ниже наименования темы приводят обозначение пояснительной записки,
которое состоит из шифра документа, включающего пятибуквенный код организации –
БГУИР; двухбуквенный код типа документа: ДП – дипломный проект или ДР –
дипломная работа; код классификационной характеристики специальности 1-ХХ ХХ ХХ;
код специализации ХХ; порядковый номер темы, присвоенный приказом по
университету, с добавлением букв ПЗ. После обозначения пояснительной записки
следуют подписи студента, руководителя, консультантов и т. д.

==== 1.2.7

Титульный лист включается в общее количество страниц пояснительной записки, но
номер страницы не проставляется.

==== 1.2.8

Реферат выполняют по ГОСТ 7.9–95. Слово РЕФЕРАТ записывают прописными буквами
полужирным шрифтом по центру, страницу не нумеруют, но включают в общее
количество страниц пояснительной записки. В реферате выделяют две составные
части: собственно реферативную и заголовочную. Заголовочная часть отражает
название темы дипломного проекта (дипломной работы), фамилию студента с
инициалами и выходные данные. В реферативной части кратко излагается содержание
дипломного проекта (дипломной работы). Основными аспектами в содержании должны
быть: предмет проектирования (исследования); цель работы; данные, относящиеся к
методам проектирования; результаты и выводы. Объем реферата ограничен текстом,
который можно разместить на одной странице пояснительной записки. Рекомендуемый
объем реферата 850–1200 печатных знаков.

==== 1.2.9

Задание по дипломному проекту (работе) заполняется согласно стандартной форме.
Пример оформления задания приведен в приложении Б. Бланк задания заполняется с
помощью печатающего устройства или печатными прописными буквами от руки.
Наименования факультета и кафедры пишут сокращенно, специальность и
специализацию обозначают кодами классификационных характеристик. В пункте 3
задания указывают исходные данные к проекту: режимы и условия работы,
характеристики сигналов, воздействий и т. д., основные показатели (параметры),
которые должны быть достигнуты при применении разработки, назначение разработки.
В пункте 4 отражают наименования разделов пояснительной записки. Пункт 5 задания
должен содержать перечень графического материала с точным указанием вида,
формата и количества листов, а также точное наименование каждого плаката. Всего
в перечне должно быть указано не менее шести листов в пересчете на формат А1. В
зависимости от темы дипломного проекта (работы) используют виды конструкторских
документов, указанных в ГОСТ 2.102–68, 2.701–2008, 2.602–95, 2.601–2006 и др.
Могут использоваться другие виды и типы схем, номенклатура, наименования и коды
которых установлены выпускающей кафедрой. В календарном плане работ указывают
наименования этапов дипломного проекта (работы), их объем и сроки выполнения
(опроцентовок). Задание по дипломному проекту (работе) и основные разделы должны
быть согласованы с консультантами. Лицевую и оборотную страницы задания не
нумеруют, но включают в общее количество страниц пояснительной записки.

==== 1.2.10

Содержание помещают сразу после задания по дипломному проекту (работе). Слово
СОДЕРЖАНИЕ пишут прописными буквами. В содержание включают заголовки всех частей
пояснительной записки, в том числе разделов и подразделов, приложений,
спецификаций и ведомость документов. Расположение заголовков в содержании должно
точно отражать последовательность и соподчиненность разделов и подразделов в
тексте пояснительной записки.

==== 1.2.11

Введение (предисловие) помещают на отдельной странице. Слово ВВЕДЕНИЕ
(ПРЕДИСЛОВИЕ) записывают прописными буквами по центру. Введение (предисловие)
должно быть кратким и четким, не должно быть общих мест и отступлений,
непосредственно не связанных с разрабатываемой темой. Объем введения не должен
превышать двух страниц. Рекомендуется следующее содержание введения
(предисловия):

* краткий анализ достижений в той области, которой посвящена тема дипломного
  проекта (работы);
* цель дипломного проектирования;
* принципы, положенные в основу проектирования, научного исследования, поиска
  технического решения;
* краткое изложение содержания разделов пояснительной записки с обязательным
  указанием задач, решению которых они посвящены.

==== 1.2.12

В основном тексте пояснительной записки анализируют существующие решения,
определяют пути достижения цели проектирования, составляют технические
требования, на основании которых разрабатывают конкретные методики и технические
решения задач, принимают схемотехнические, алгоритмические, программные и
конструктивно-технологические решения. Общие требования к основному тексту
пояснительной записки: четкость и логическая последовательность изложения
материала, убедительность аргументации, краткость и ясность формулировок,
исключающих неоднозначность толкования, конкретность изложения результатов,
доказательств и выводов.

==== 1.2.13

Запрещается включать в дипломный проект (работу) общие сведения из учебников,
учебных пособий, монографий, статей, систем подсказок (help), интернет-ресурсов
и других источников.

==== 1.2.14

В экономическом разделе, в разделе охраны труда или экологической безопасности,
энерго- и ресурсосбережения рассматриваются вопросы, предусмотренные заданием по
дипломному проектированию. Для инженерно-экономических специальностей
рассматриваются вопросы, предусмотренные заданием по
конструкторско-технологической части проекта (работы).

==== 1.2.15

Заключение пишут на отдельной странице. Слово ЗАКЛЮЧЕНИЕ записывают прописными
буквами полужирным шрифтом по центру строки. В заключении необходимо перечислить
основные результаты, характеризующие степень достижения цели проекта и
подытоживающие его содержание. Результаты следует излагать в форме констатации
фактов, используя слова: «изучены», «исследованы», «сформулированы», «показано»,
«разработана», «предложена», «подготовлены», «изготовлена», «испытана» и т. п.
Текст перечислений должен быть кратким, ясным и содержать конкретные данные.
Объем заключения не должен занимать более полутора-двух страниц пояснительной
записки.

==== 1.2.16

СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ следует оформлять по ГОСТ 7.1–2003. Примеры
оформления приведены в подразделе 2.8.

==== 1.2.17

Правила оформления приложений изложены в ГОСТ 2.105–95 (см. подраздел 2.7).

==== 1.2.18

ПЕРЕЧЕНЬ ЭЛЕМЕНТОВ схем электрических принципиальных оформляется по ГОСТ
2.701–2008 в виде самостоятельного документа на отдельных листах формата А4 и
помещается в пояснительной записке перед ведомостью документов. Пример
оформления перечня элементов приведен в приложении Г. Элементы располагаются в
порядке латинского алфавита. В дипломных проектах (работах), не содержащих
электрических принципиальных схем, приводится перечень оборудования
разрабатываемой информационной системы.

==== 1.2.19

ВЕДОМОСТЬ ДОКУМЕНТОВ соответствует составу дипломного проекта (работы) и
является последним обязательным листом пояснительной записки. Форма ведомости и
ее оформление приведены в приложении Д, где обозначения и наименования для
графического материала должны соответствовать графам 1 и 2 рисунка 3.1 основной
надписи графической части.

=== 1.3 Обязанности студента (курсанта), руководителя и консультанта

==== 1.3.1

Студент (курсант) обязан:

* самостоятельно выполнить дипломный проект (работу) и по результатам
  проектирования (разработки) сделать доклад на заседании ГЭК;
* оформить пояснительную записку и графическую часть в соответствии с
  требованиями действующих стандартов ЕСКД, ЕСТД, ЕСПД;
* нести персональную ответственность за принятые решения и достоверность их
  обоснования;
* принимать участие в разработке заданий и этапов проектирования, соблюдать
  сроки выполнения календарного плана;
* еженедельно информировать руководителя о ходе выполнения дипломного проекта
  (работы);
* в установленные выпускающей кафедрой сроки представлять консультанту от
  кафедры все выполненные к этим моментам проектные материалы для опроцентовок.

==== 1.3.2

Руководитель обязан:

* составить и выдать задание по дипломному проекту (работе);
* разработать календарный план на весь период проектирования;
* рекомендовать студенту (курсанту) необходимую литературу, справочные и
  архивные материалы, типовые проекты и другие источники по теме дипломного
  проекта (работы);
* проводить консультации, проверять результаты расчетов и экспериментов;
* контролировать ход выполнения работы и нести свою долю ответственности за ее
  выполнение вплоть до защиты дипломного проекта (работы);
* оказывать помощь в подготовке доклада об основных результатах, полученных в
  ходе разработки темы дипломного проекта (работы).
* составить отзыв о дипломном проекте и работе студента (курсанта) над проектом,
  согласно пункту 1.4.1.

==== 1.3.3

Консультант от выпускающей кафедры обязан:

* оказывать помощь в формировании задач проектирования, отвечающих содержанию
  специальности (специализации);
* консультировать по вопросам выбора методик решения сформулированных задач,
  расчета и проектирования, обоснования принимаемых студентом (курсантом)
  решений;
* контролировать сроки выполнения основных этапов проектирования и ставить в
  известность кафедру об их нарушении и причинах, вызвавших их;
* осуществлять технологический контроль («Т. контр.») графической и текстовой
  документации. Технологический контроль предполагает проверку соответствия
  принятых в процессе проектирования технических решений состоянию развития
  данной отрасли техники, простоты реализации разработанного изделия (продукта),
  его технологичности, а также возможности использования в сфере современных
  информационных технологий;
* принимать участие в работе рабочей комиссии;
* оценить полноту дипломного проекта (работы), готовность студента (курсанта) к
  защите в ГЭК и проинформировать об этом кафедру;
* выдавать индивидуальное задание по вопросу охраны труда, или экологической
  безопасности, или энерго- и ресурсосбережения.

==== 1.3.4

Консультанты от других кафедр обязаны:

* выдать задание студенту в течение первых двух недель преддипломной практики;
* консультировать студента по теме задания в соответствии с утвержденным
  графиком;
* проверить правильность выполнения выданного задания;
* представить заведующему выпускающей кафедрой до начала работы рабочих комиссий
  докладную записку о выполнении каждым студентом (курсантом) соответствующего
  раздела дипломного проекта (дипломной работы).

==== 1.3.5

Нормоконтролер обязан:

* проверить соблюдение в разработанной документации норм и требований,
  установленных в межгосударственных и республиканских стандартах, а также в
  стандартах университета;
* проверить соответствие графических и текстовых документов требованиям
  стандартов ЕСКД;
* оценить уровень использования в процессе проектирования прогрессивных методов
  стандартизации и унификации. Нормоконтроль осуществляют преподаватели
  университета, назначенные выпускающей кафедрой.

==== 1.3.6

Графики опроцентовок дипломных проектов (работ), консультаций по нормам и
требованиям ЕСКД, ЕСТД, ЕСПД, преподавателей-консультантов разрабатываются
профилирующей кафедрой в установленном порядке и доводятся до сведения студентов
(курсантов).

==== 1.3.7

В случае недобросовестного отношения студента (курсанта) к работе кафедра
принимает решение о целесообразности дальнейшей работы над проектом, информируя
декана факультета.

=== 1.4 Подготовка к защите дипломного проекта

==== 1.4.1

Законченный дипломный проект, подписанный студентом (курсантом) и
консультантами, представляется руководителю, который составляет на него отзыв. В
отзыве руководителя дипломного проекта должны быть отмечены:

* актуальность темы дипломного проекта (работы);
* степень решенности поставленной задачи;
* степень самостоятельности и инициативности студента (курсанта);
* умение студента (курсанта) пользоваться специальной литературой;
* способности студента (курсанта) к инженерной или исследовательской работе;
* возможности присвоения выпускнику соответствующей квалификации. Пример
  оформления отзыва руководителя приведен в приложении Е.

==== 1.4.2

Дипломный проект (работу) и отзыв руководителя студент (курсант) должен
представить в рабочую комиссию для проверки не позднее чем за две недели до
работы ГЭК.

==== 1.4.3

Рабочая комиссия проверяет соответствие названия темы проекта (работы) названию,
утвержденному в приказе, соответствие содержания проекта (работы) содержанию
заданий на проектирование, а также полноту представленных материалов;
заслушивает сообщение студента (курсанта), определяет его готовность к защите в
ГЭК и сообщает ему одно из решений комиссии:

* об одобрении проекта (работы);
* о неготовности проекта (работы) к защите;
* о необходимости доработки (с точным указанием требуемых исправлений).

Рабочая комиссия не рассматривает дипломный проект (работу) студента (курсанта),
не выполнившего в полном объеме соответствующий раздел по заключению
консультанта от других кафедр.

==== 1.4.4

Для доработки проекта (работы) студенту (курсанту) предоставляется срок не более
одной недели. После внесения исправлений студент (курсант) повторно представляет
в рабочую комиссию дипломный проект (работу) для рассмотрения.

==== 1.4.5

На основании вывода рабочей комиссии допуск студента (курсанта) к защите
фиксируется подписью заведующего кафедрой на титульном листе пояснительной
записки к дипломному проекту (работе). При этом заведующий кафедрой имеет право
перенести защиту дипломного проекта (работы) студента (курсанта), нарушившего
календарный план, на последний день работы ГЭК. Если заведующий кафедрой на
основании вывода рабочей комиссии не считает возможным допустить студента
(курсанта) к защите, этот вопрос рассматривается на заседании кафедры с участием
руководителя или (и) консультанта дипломного проекта (работы). При отрицательном
заключении кафедры выписка из протокола заседания представляется через декана
факультета на утверждение ректору, после чего студента (курсанта) информируют о
том, что он не допускается к защите дипломного проекта (работы).

==== 1.4.6

Дипломный проект (работа), допущенный выпускающей кафедрой к защите,
направляется заведующим кафедрой на рецензию. Рецензенты дипломных проектов
(работ) утверждаются деканом факультета по представлению заведующего кафедрой из
числа профессорско-преподавательского состава других кафедр, специалистов
производства, научных учреждений, педагогического состава других вузов не
позднее одного месяца до защиты.

==== 1.4.7

В рецензии должны быть отмечены:

* объем пояснительной записки и графического материала;
* актуальность темы дипломного проекта (работы);
* степень соответствия дипломного проекта (работы) заданию;
* логичность построения пояснительной записки;
* наличие обзора литературы по теме дипломного проекта (работы), его полнота и
  последовательность анализа;
* полнота описания методики расчета или проведенных исследований, изложения
  собственных расчетных, теоретических и экспериментальных результатов, оценка
  достоверности полученных выражений и данных;
* наличие аргументированных выводов по результатам дипломного проекта (работы);
* практическая значимость дипломного проекта (работы), возможность использования
  полученных результатов;
* недостатки и слабые стороны дипломного проекта (работы);
* замечания по оформлению пояснительной записки к дипломному проекту и стилю
  изложения материала;
* отметка дипломного проекта (работы) по 10-балльной системе. Пример оформления
  рецензии приведен в приложении Ж.

==== 1.4.8

Студент (курсант) должен быть ознакомлен с рецензией не менее чем за сутки до
защиты проекта (работы) перед ГЭК. Изменения по замечаниям рецензента в готовый
дипломный проект не вносятся. Рецензия, отзыв руководителя, акт (справка) о
внедрении не подшиваются в пояснительную записку, а предъявляются ГЭК как
отдельные самостоятельные документы.

==== 1.4.9

Руководители дипломных проектов (работ) от сторонних организаций и рецензенты
оформляют акт приемки выполненных работ согласно договору подряда, который
является основанием для оплаты труда. Подписанные акты сдают секретарю ГЭК.

=== 1.5 Защита дипломного проекта (работы)

==== 1.5.1

К защите дипломного проекта (работы) допускаются студенты (курсанты), полностью
выполнившие учебный план, учебные программы, программы практик (в том числе
преддипломной практики), сдавшие государственный экзамен, выполнившие в полном
объеме задание на дипломный проект (работу). Допуск к защите осуществляется в
соответствии с пунктами 1.4.3, 1.4.4 и 1.4.5.

==== 1.5.2

До начала работы ГЭК деканом факультета представляются списки студентов
(курсантов), допущенных к защите дипломных проектов, и учебные карточки
студентов (курсантов) с указанием полученных ими оценок по изученным
дисциплинам, курсовым проектам (работам), учебной и производственной практикам.

==== 1.5.3

Студенты (курсанты), допущенные к защите дипломного проекта (работы), минимум за
один день до назначенного кафедрой дня защиты должны явиться к секретарю ГЭК для
уточнения времени защиты, имея при себе пояснительную записку, графический
материал, отзыв и рецензию. В ГЭК также следует представлять (при наличии) акты
или справки (приложения И, К), подтверждающие научную и практическую значимость
выполненного дипломного проекта (работы), перечень публикаций и изобретений
студента (курсанта).

==== 1.5.4

Защита дипломных проектов (работ) производится на открытом заседании ГЭК. На
защиту могут быть приглашены руководитель, рецензент, консультанты,
представители предприятий и организаций.

==== 1.5.5

Защита дипломных проектов (работ), содержание которых не может быть вынесено на
общее обсуждение, проводится в установленном порядке.

==== 1.5.6

На защиту каждого дипломного проекта (работы) отводится не более 30 мин. Для
доклада о содержании дипломного проекта (работы) студенту (курсанту)
предоставляется время до 15 мин. Доклад на заседании ГЭК может быть выполнен в
форме презентации, причем количество слайдов определяет автор проекта. Слайды
могут содержать дополнительные материалы, раскрывающие особенности темы
дипломного проекта (работы), задачи проектирования, суть выполненных
теоретических, экспериментальных и инженерных решений, а также выводы,
заключение и прочие полезные сведения. После доклада выпускник отвечает на
вопросы членов ГЭК. Вопросы могут быть общего характера в пределах дисциплин
специальности и специализации, изучаемых на протяжении всего обучения в
университете, или связаны с темой выполненного проекта (работы). Лица,
присутствующие на защите дипломного проекта (работы) и не являющиеся членами
ГЭК, не могут задавать вопросы студенту (курсанту) и влиять на ход защиты. Затем
может выступить рецензент, если он присутствует на заседании ГЭК или
зачитывается его рецензия. На имеющиеся замечания рецензента студент (курсант)
должен дать необходимые разъяснения. После этого со своим отзывом выступает
руководитель дипломного проекта или (в его отсутствие) отзыв зачитывается в его
отсутствие. Защита заканчивается предоставлением выпускнику заключительного
слова, в котором он вправе высказать свое мнение по замечаниям и рекомендациям,
сделанным в процессе обсуждения проекта.

==== 1.5.7

После окончания защиты дипломных проектов (работ) ГЭК продолжает свою работу на
закрытой части заседания, на котором с согласия председателя комиссии могут
присутствовать руководители и рецензенты дипломных проектов (работ) при решении
вопросов, касающихся только их дипломников. В ходе закрытого заседания члены
ГЭК:

* оценивают результаты защиты каждого дипломного проекта (работы), учитывая при
  этом его (ее) практическую ценность, содержание доклада и ответы студента
  (курсанта) на вопросы, отзыв руководителя дипломного проекта (работы) и
  рецензию;
* принимают решения о выдаче дипломов о высшем образовании, в том числе с
  отличием, и оформляют протокол. В соответствии с Законом Республики Беларусь
  №252–3 от 11 июня 2007 года документы о высшем образовании с отличием выдаются
  лицам, имеющим по итогам обучения в высших учебных заведениях, включая
  итоговую аттестацию, не менее 75 % отметок 10 и 9 баллов, а остальные отметки
  – не ниже 7 баллов. Отметка за выполнение и защиту дипломного проекта
  выставляется по итогам открытого голосования большинством голосов членов ГЭК.
  При равном числе голосов голос председателя является решающим. Результаты
  защиты дипломных проектов, решения о присвоении квалификации, выдаче дипломов
  о высшем образовании, в том числе с отличием, оглашаются в этот же день после
  оформления соответствующих протоколов.

==== 1.5.8

Дипломный проект (работа) после защиты хранится в архиве университета.

==== 1.5.9

Повторная итоговая аттестация студентов (курсантов), не сдавших государственный
экзамен, не допущенных к защите дипломного проекта (работы), не защитивших
дипломный проект (работу), проводится в соответствии с графиком работы ГЭК
последующих трех учебных лет. При этом государственный экзамен сдается по тем
учебным дисциплинам, которые были определены учебными планами, по которым
проходило обучение в год их отчисления.

==== 1.5.10

Студентам (курсантам), не сдавшим государственный экзамен, не защитившим
дипломный проект (работу) по уважительной причине (болезнь, семейные
обстоятельства, стихийные бедствия и др.), подтвержденной документально,
ректором университета на основании заявления студента (курсанта) и представления
декана факультета продлевается срок обучения, установленный в соответствии с
причиной непрохождения итоговой аттестации.

== 2 ТРЕБОВАНИЯ К ПОЯСНИТЕЛЬНОЙ ЗАПИСКЕ

=== 2.1 Общие положения

==== 2.1.1

Пояснительную записку выполняют с применением печатающих и графических устройств
вывода ПЭВМ или рукописным способом. При печати с помощью текстового редактора
ПЭВМ используется гарнитура шрифта Times New Roman размером шрифта 13–14 пунктов
с межстрочным интервалом, позволяющим разместить 40 ± 3 строки на странице. При
рукописном способе используют шариковую ручку с пастой черного, синего или
фиолетового цвета. Высота букв и цифр должна быть не менее 3,5 мм. Номера
разделов, подразделов, пунктов и подпунктов следует выделять полужирным шрифтом.
Заголовки разделов рекомендуется оформлять полужирным шрифтом размером 14–16
пунктов, а подразделов – полужирным шрифтом 13–14 пунктов. Для акцентирования
внимания на определенных элементах допускается использовать курсивное и
полужирное начертание.

==== 2.1.2

Текст располагают на одной стороне листа формата А4 с соблюдением размеров полей
и интервалов, указанных в приложении Л.

==== 2.1.3

Абзацы в тексте начинают отступом 1,25 или 1,27 см, устанавливаемым в Word в
диалоговом окне Абзац, или 15–17 мм при выполнении записи рукописным способом
(см. приложение Л).

==== 2.1.4

Все части пояснительной записки необходимо излагать на одном языке – на русском
или белорусском. Для студентов – граждан иностранных государств, получающих
высшее образование на английском языке, допускается все части излагать на языке
обучения.

==== 2.1.5

Описки и графические неточности, обнаруженные в тексте пояснительной записки,
выполненной рукописным способом, допускается исправлять подчисткой,
закрашиванием белой краской и нанесением на том же месте исправленного текста.
Помарки и следы не полностью удаленного прежнего текста не допускаются.

==== 2.1.6

Пояснительная записка должна быть сшита в жестком переплете (специальной папке
для дипломных проектов (работ)).

=== 2.2 Рубрикации, заголовки и содержание

==== 2.2.1

Текст пояснительной записки разделяют на логически связанные части – разделы,
при необходимости – на подразделы, а подразделы – на пункты.

==== 2.2.2

Разделы должны иметь порядковые номера, обозначаемые арабскими цифрами без точки
в конце и записанные с абзацного отступа. Подразделы нумеруют в пределах
раздела, к которому они относятся.

==== 2.2.3

Иногда внутри подраздела выделяют более мелкие смысловые единицы – пункты. В
подобных случаях пункты нумеруют в пределах подраздела. Пункты при необходимости
могут быть разбиты на подпункты, которые нумеруются в пределах каждого пункта.

==== 2.2.4

Если в пояснительной записке выделены только разделы, то пункты нумеруют в
пределах раздела.

==== 2.2.5

Каждый раздел и подраздел должен иметь краткий и ясный заголовок. Пункты, как
правило, заголовков не имеют. Заголовки разделов записывают прописными буквами
без точки в конце заголовка. Заголовки подразделов записывают строчными буквами,
начиная с первой прописной. Заголовки не подчеркивают. Переносы слов в
заголовках не допускаются. Если заголовок состоит из двух предложений, их
разделяют точкой. Если заголовки раздела или подраздела занимают несколько
строк, то строки выравниваются по первой букве заголовка в соответствии с
приложением Л.

==== 2.2.6

Каждый раздел пояснительной записки рекомендуется начинать с новой страницы.
Между заголовком раздела (подраздела) и текстом оставляют пробельную строку –
при компьютерном способе выполнения записки; интервал шириной 15 мм – при
рукописном способе (см. приложение Л). Между заголовками разделов и входящих в
него подразделов допускается помещать небольшой вводный текст, предваряющий
подраздел.

==== 2.2.7

Перечень всех разделов и подразделов, включающий порядковые номера и заголовки,
оформляют в виде содержания – обязательного элемента пояснительной записки.
Содержание помещают непосредственно за заданием на проектирование и включают в
общую нумерацию страниц. Слово СОДЕРЖАНИЕ записывают прописными буквами
полужирным шрифтом 14–16 пунктов и располагают по центру строки. Между словом
СОДЕРЖАНИЕ и самим содержанием оставляют промежуток, равный пробельной строке. В
содержании заголовки выравнивают, соподчиняя по разделам, подразделам и пунктам
(если последние имеют заголовки), смещая вертикали вправо относительно друг
друга на 2 знака. В содержании каждый заголовок соединяют отточием с номером
страницы, расположенным в столбце справа.

==== 2.2.8

Страницы пояснительной записки нумеруют арабскими цифрами в правом нижнем углу.
Титульный лист, лист с рефератом и лист задания включают в общую нумерацию, но
номер страницы на них не ставят. В общую нумерацию страниц включают все
приложения.

=== 2.3 Основные правила изложения текста

==== 2.3.1

Текст пояснительной записки должен быть четким и логично изложенным, не
допускать различных толкований. При изложении обязательных требований в тексте
должны применяться слова «должен», «следует», «необходимо», «требуется, чтобы»,
«не допускается», «запрещается». При изложении других положений рекомендуется
использовать слова: «допускают», «указывают», «применяют». В тексте следует
применять научно-технические термины, обозначения и определения, установленные
действующими стандартами, а при их отсутствии – принятые в научно-технической
литературе. Запрещается применять иностранные термины при наличии равнозначных
слов и терминов в русском языке.

==== 2.3.2

Текст излагают с соблюдением правил орфографии и пунктуации. Следует обратить
внимание на абзацы, перечисления, употребление чисел, символов и размерностей.

==== 2.3.3

Небольшие по объему обособленные по смыслу части текста выделяют абзацами.

==== 2.3.4

В пояснительной записке часто используют перечисления.

==== 2.3.5

Если перечисление простое, т. е. состоит из слов и словосочетаний, то каждый
элемент необходимо записывать с новой строки, начиная с абзацного отступа и
знака «тире», а в конце ставить точку с запятой.

==== 2.3.6

Простое перечисление допускается писать в подбор с текстом, отделяя слова или
словосочетания друг от друга запятой.

==== 2.3.7

При сложном перечислении, состоящем из нескольких предложений, каждый элемент
перечисления нумеруют и пишут с прописной буквы, начиная с абзацного отступа, а
в конце ставят точку.

==== 2.3.8

Если в пояснительной записке необходимо сделать ссылки на элементы перечисления,
их обозначают строчными буквами русского алфавита со скобкой. При дальнейшей
детализации перечислений используются арабские цифры со скобкой, а запись
производится с абзацного отступа, соответствующего уровню перечисления (см.
приложение Л).

==== 2.3.9

При ссылке в тексте на элемент перечисления следует писать без сокращения слово
«пункт» или «подпункт» и после номера или буквы убирать скобку.

==== 2.3.10

Все элементы перечисления должны подчиняться вводной фразе, предшествующей
перечислению. Не допускается обрывать вводную фразу перед перечислениями на
предлогах или союзах «из», «на», «то», «как» и т. д.

==== 2.3.11

В тексте пояснительной записки (кроме формул, таблиц и рисунков) следует писать
словами: – математический знак «–» минус перед отрицательными значениями
величин; – математические знаки > (больше), < (меньше), = (равно), а также знаки
№ (номер), % (процент),  (диаметр), sin (синус), cos (косинус) и т. д., не
имеющие при себе числовых значений.

==== 2.3.12

В тексте числа от одного до девяти без единиц измерений следует писать словами,
свыше девяти – цифрами. Дробные числа необходимо приводить в виде десятичных
дробей. Перед числами с размерностями не рекомендуется ставить предлог «в» или
знак тире «–». Приводя наибольшее или наименьшее значение величин, следует
применять словосочетание «должно быть не более (не менее)». Если в пояснительной
записке приводят диапазон числовых значений одних и тех же единиц физической
величины, то обозначение единицы физической величины следует указывать после
последнего числового значения диапазона. Числовые значения величин следует
указывать с максимально допустимой степенью точности. Порядковые числительные
пишут цифрами с наращением однобуквенного падежного окончания, если
предпоследняя буква числительного глас-ная, и двухбуквенного окончания, если
предпоследняя буква согласная. Количественные числительные до десяти без единиц
измерений следует писать словами. Количественные числительные свыше десяти
обозначают цифрой без наращения.

==== 2.3.13

В пояснительной записке следует применять единицы физических величин, их
наименования и обозначения в соответствии с ГОСТ 8.417–2002. В приложении Т
приведены буквенные обозначения величин и размерностей, наиболее часто
употребляемые в проектах (работах). Применение других систем обозначений
физических величин не допускается. Если в пояснительной записке необходимо
использовать сведения из литературных источников, в которых применены иные
системы обозначений, то их нужно перевести в систему СИ. Коэффициенты перевода
приведены в приложении У с точностью, достаточной для инженерных расчетов.

==== 2.3.14

Не следует помещать обозначения единиц физических величин в одной строке с
формулами, выраженными в буквенной форме. В тех случаях, когда в формулу
подставляют числовые значения и вычисляют результат, обозначение единицы
физической величины пишут за результатом с пробелом, равным одному знаку, или
3–4 мм при рукописном способе.

==== 2.3.15

Применяемые в пояснительной записке условные буквенные обозначения, в том числе
индексы, изображения или знаки должны соответствовать принятым в нормативной
документации и действующих стандартах.

===== 2.3.15.1

Чтобы указать различие нескольких физических величин, обозначенных одной и той
же буквой, применяют верхние и нижние индексы.

===== 2.3.15.2

В качестве верхних индексов рекомендуется применять арабские цифры, знаки прим
(′), звездочку (\*) и букву (Т).

===== 2.3.15.3

Нижними индексами при буквенных обозначениях могут быть:
* цифры, обозначающие порядковые номера;
* буквы греческого и латинского алфавитов, указывающие на связь с физическими
  величинами, обозначенными соответствующими символами;
* буквы русского алфавита, соответствующие одной или нескольким начальным буквам
  термина

===== 2.3.15.4

Индексы, составленные из двух-трех сокращенных русских слов, пишут прямым
шрифтом с точками между сокращениями.

===== 2.3.15.5

Если в состав индекса входит несколько цифр или букв латинского и (или)
греческого алфавитов, то их отделяют друг от друга запятой.

=== 2.4 Основные правила написания математических формул

==== 2.4.1

При изложении выводов из математических формул не рекомендуется использовать
выражения: «мы получили», «мы нашли», «определили», «получится», «выразится в
виде», «будем иметь» и т. п. Следует употреблять слова: «получаем»,
«определяем», «находим», «преобразуем к виду» и т. д. Связующие слова
«следовательно», «откуда», «поскольку», «так как», «или» и другие располагают в
начале строк, а знаки препинания ставят непосредственно за формулой.

Если формулам предшествует фраза с обобщающим словом, то после нее необходимо
ставить двоеточие.

==== 2.4.2

Математические формулы должны быть вписаны отчетливо с точным размещением
знаков, цифр и букв. Каждую букву в формулах и тексте необходимо записывать в
точном соответствии с алфавитом. Для того чтобы в формулах различать символы
сходного начертания, принято буквы латинского алфавита печатать курсивом, а
русского и греческого – прямым шрифтом. Образцы букв приведены в приложении Ф.
На протяжении всей пояснительной записки необходимо соблюдать следующие размеры
в формулах: 3–4 мм для строчных и 6–8 мм для прописных букв и цифр. Все индексы
и показатели степени должны быть в 1,5–2 раза меньше. Знаки сложения, вычитания,
корня, равенства и т. д. необходимо размещать так, чтобы их середина была
расположена строго против горизонтальной черты дроби.

==== 2.4.3

Формулы, как правило, располагают на отдельных строках по центру и отделяют от
текста пробельными строками. В приложении М приведены примеры расположения
формул с указанием расстояний между строками текста. Рекомендуются следующие
межтекстовые промежутки для размещения формул:– 6 интервалов при печатном
способе или 24 мм при рукописном для простейших однострочных формул; – 8
интервалов при печатном способе или 32 мм при рукописном для однострочных
формул, содержащих знаки Σ, Π, ∫ и т. п.; – для формул, содержащих две строки и
более, а также для сложных выражений необходимо выставлять межтекстовые
промежутки в соответствии с рекомендациями пунктов 2.4.2 и 2.4.3.

==== 2.4.4

Короткие однотипные формулы допускается располагать на одной строке, разделяя
точкой с запятой.

==== 2.4.5

При необходимости допускается перенос части математического выражения на
следующую строку. Причем знак операции, на котором сделан перенос, пишут два
раза – в конце первой и в начале второй строки. При переносе формулы на знаке
умножения вместо «·» применяют знак «×». Не допускаются переносы на знаке
деления, а также выражений, относящихся к знакам корня, интеграла, логарифма,
тригонометрических функций и т. п.

==== 2.4.6

Все формулы, расположенные в отдельных строках, нумеруют. Одним номером отмечают
также группу однотипных формул, размещенных на одной строке. Формулы
рекомендуется нумеровать в пределах раздела, к которому они относятся. Номер
формулы должен состоять из порядкового номера раздела и отделенного от него
точкой порядкового номера формулы. Если в разделе одна формула, ее также
нумеруют. Если в пояснительной записке формул не более 10, то разрешается
применять сквозную нумерацию. Формулы, помещаемые в приложения, должны иметь
отдельную нумерацию в пределах каждого приложения. Вначале указывают обозначение
приложения, затем ставят точку и приводят порядковый номер формулы в данном
приложении.

==== 2.4.7

Порядковый номер формулы записывают арабскими цифрами в круглых скобках у
правого края строки.При переносе части формулы с одной строки на другую номер
располагают на последней строке. Номер сложной формулы (в виде дроби) записывают
так, чтобы середина номера располагалась на уровне черты дроби. Ссылки в тексте
пояснительной записки на порядковый номер формулы следует приводить в круглых
скобках с обязательным указанием слова «формула», «уравнение», «выражение»,
«равенство», «передаточная функция» и т. д. После формулы следует помещать
перечень и расшифровку приведенных в формуле символов, которые не были пояснены
ранее. Перечень начинают со слова «где», которое приводят с новой строки без
абзацного отступа; после слова «где» двоеточие не ставят. В этой же строке
помещают первый поясняющий символ. Символы необходимо отделять от расшифровок
знаком тире, выравнивая перечень по символам. Каждую расшифровку заканчивают
точкой с запятой. Размерность символа или коэффициента указывают в конце
расшифровки и отделяют запятой. Разрешается перечень и расшифровку
использованных символов располагать в подбор. Иногда перечень и расшифровку
начинают со слов «здесь» или «в формуле обозначено». В этих случаях после
формулы ставят точку, а слова «здесь» или «в формуле обозначено» записывают с
абзацного отступа с прописной буквы.

=== 2.5 Основные требования к иллюстрациям

==== 2.5.1

Виды иллюстраций (чертежи, схемы, графики, осциллограммы, цикло- и тактограммы,
фотографии) и их количество в пояснительной записке определяет автор проекта
(работы). Следует исходить из того, что иллюстрации – наиболее простой и
наглядный способ изложения тех частей пояснительной записки, которые требуют
длительного текстового описания.

==== 2.5.2

Каждая иллюстрация должна быть четкой, ясной по смыслу и связанной с текстом, а
также располагаться по возможности ближе к разъясняющей части текста.
Допускается располагать иллюстрации в конце пояснительной записки в виде
приложения.

==== 2.5.3

Все иллюстрации независимо от их вида и содержания в технической литературе
принято называть рисунками. В пояснительной записке рекомендуются размеры
рисунков приблизительно 92 × 150 мм и 150 × 240 мм. Выбор конкретного размера
зависит от количества изображаемых деталей, сложности связей между ними,
необходимого количества надписей на рисунке. Рисунок следует располагать после
абзаца, в котором дана первая ссылка на него. Можно размещать на отдельном листе
несколько рисунков. В таком случае помещать этот лист следует за страницей, где
дана ссылка на последний из размещенных рисунков. Иллюстрацию, помещенную в
тексте между абзацами, располагают по центру и отделяют от текста и
подрисуночной подписи одной пробельной строкой (приложение Н).

==== 2.5.4

Иллюстрация должна быть расположена таким образом, чтобы ее было удобно
рассматривать без поворота пояснительной записки или с поворотом на 90º по
часовой стрелке.

==== 2.5.5

Каждый рисунок сопровождают подрисуночной подписью. Подпись должна содержать
слово «Рисунок» без сокращения и порядковый номер иллюстрации арабскими цифрами.
Подпись иллюстраций, расположенных в приложениях, должна содержать слово
«Рисунок», буквенное обозначение приложения и порядковый номер иллюстрации в
приложении, между которыми ставится точка. Если в приложении помещена одна
иллюстрация, ее обозначают «Рисунок А.1». Все иллюстрации должны иметь
наименования, которые записывают после номера рисунка через знак тире с
прописной буквы. Точки после номера и наименования рисунка не ставят. Подпись и
наименование располагают, выравнивая по центру относительно рисунка. Допускается
выносить в подрисуночную подпись расшифровку условных обозначений, частей и
деталей иллюстрации. Все пояснительные данные помещают между рисунком и
подрисуночной подписью. Расшифровки пишут в подбор, отделяя их друг от друга
точкой с запятой. Цифры, буквы, другие условные обозначения позиций на рисунке
приводят без скобок, отделяя от расшифровок знаками тире. Длина строк с
пояснениями не должна выходить за границы рисунка. Стандартные буквенные
позиционные обозначения, приведенные на рисунке, не расшифровывают. Если
обозначения, приведенные на иллюстрации, разъясняются в тексте пояснительной
записки, то расшифровки в подрисуночных подписях не допускаются. Не разрешается
часть деталей иллюстрации пояснять в тексте, а другую – расшифровывать в
подрисуночной подписи. Все подрисуночные подписи в пояснительной записке следует
выполнять единообразно.

==== 2.5.6

В тексте пояснительной записки должны быть даны ссылки на все иллюстрации без
исключения. В ссылках рекомендуется использовать обороты «в соответствии с
рисунком 2», «на рисунке 5.1 изображены…», «(см. рисунок 2)» и т. п. Рисунок,
как правило, выполняется на одной странице. Если рисунок не помещается на одной
странице, то допускается перенос его части на другие страницы. В этом случае в
подписях ко второй, третьей и другим частям изображения повторяют подпись
«Рисунок» и номер иллюстрации, сопровождая словами «лист 2», «лист 3» и т. д.

==== 2.5.7

Иллюстрации, как и другие виды конструкторских документов, должны быть выполнены
в соответствии с требованиями ЕСКД, ЕСТД и ЕСПД. Однако если на документах по
ЕСКД, ЕСТД и ЕСПД представляют всю (без исключения) информацию, поясняющую
назначение функциональных частей, типы элементов и их номинальные параметры, все
связи с источниками питания, состояние функциональных частей и устройств,
возможности их регулировки и т. д., то на иллюстрациях к тексту должна быть
представлена только та информация, которая непосредственно касается сути
излагаемых вопросов. При использовании для иллюстраций чертежей и схем, уже
разработанных по ЕСКД, ЕСТД и ЕСПД, их необходимо доработать:

* исключить рамки, угловые штампы, спецификации, технические характеристики и т.
  п.;
* заменить элементы, не имеющие прямого отношения к сути рассматриваемого
  вопроса, изображением прямоугольника из штрихпунктирных линий;
* максимально сократить число надписей. Другие рекомендации даны в третьем
  разделе стандарта предприятия при изложении правил выполнения и оформления
  конкретных видов чертежей, схем, графиков и других конструкторских документов.

==== 2.5.8

Во всей пояснительной записке следует соблюдать единообразие при выполнении
иллюстраций, оформлении подрисуночных подписей, всех надписей, размерных и
выносных линий, использовании условных обозначений.Иллюстрации следует выполнять
с помощью компьютерной техники или шариковой ручкой с темной (черной или синей)
пастой, или карандашом средней твердости с помощью чертежных инструментов. При
выполнении иллюстраций разрешается использовать либо только карандаш, либо
только шариковую ручку с пастой одного цвета по всей пояснительной записке. Если
пояснительная записка выполнена в текстовом редакторе ПЭВМ, то все иллюстрации
должны быть оформлены с помощью графического редактора, если текст пишется от
руки, то черной тушью. При этом допускается цветное выполнение отдельных
иллюстраций. Надписи на всех иллюстрациях следует выполнять стандартным шрифтом
с высотой строчных букв не менее 2,5 мм. Прописные буквы в подписях и условных
графических обозначениях элементов, цифры, обозначающие нумерацию элементов или
масштабность координатных шкал, другие числовые значения на графиках следует
писать на 1/3 крупнее строчных букв. Разрешается при необходимости буквенные
обозначения элементов (устройств) на схеме, их порядковые номера выполнять
несколько большего размера.

=== 2.6 Построение таблиц

==== 2.6.1

Таблицы применяют для того, чтобы упростить изложение текста, содержащего
достаточно большой по объему фактический материал, придать этому материалу более
компактную, удобную форму для анализа и расчетов, чтобы повысить обоснованность
и достоверность принимаемых решений. В виде таблицы обычно оформляют:

* сведения справочного характера;
* значения функций, используемые при графических методах расчета;
* данные экспериментальных исследований функциональных элементов и устройств, по
  которым определяют их статические и динамические характеристики;
* результаты математического моделирования технических систем с автоматическим
  управлением и др. Таблицу в зависимости от ее размера рекомендуется помещать
  непосредственно за абзацем, в котором на нее впервые дана ссылка, либо на
  следующей странице. При необходимости допускается оформлять таблицу в виде
  приложения к пояснительной записке.

==== 2.6.2

Все таблицы в тексте должны быть пронумерованы арабскими цифрами и иметь
текстовый заголовок, причем слово «таблица» не сокращают. Номер таблицы и
заголовок разделяют знаком тире. Слово «Таблица» начинают писать на уровне левой
границы таблицы. Таблицы рекомендуется нумеровать в соответствии с принятой
системой нумерации формул и рисунков. Таблицы в каждом приложении снабжают
отдельной нумерацией с обязательным указанием обозначения приложения. Заголовок
должен быть кратким и точно отражать содержание таблицы. Строки с заголовком не
должны выходить за правую и левую границы таблицы.

==== 2.6.3

Таблицы оформляют в соответствии с рисунками 2.1–2.5 и приложением Л. Таблицу
вместе с заголовком отделяют от предыдущего и последующего текста пробельной
строкой. Если заголовок состоит из нескольких строк, то вторая и последующие
строки располагаются под текстом заголовка в первой строке, как показано на
рисунке 2.2, при этом используется выравнивание абзаца «по левому краю». Точки
после номера и заголовка таблицы не ставят. Заголовок и саму таблицу пробельной
строкой не разделяют.

==== 2.6.4

Слева, справа и снизу таблицы рекомендуется ограничивать линиями. Если в конце
страницы таблица не заканчивается, то горизонтальную ограничивающую черту
допускается не проводить (рисунок 2.2).При продолжении таблицы головку
допускается заменять нумерацией граф. В этом случае нумерацию помещают и в
первой части таблицы после головки. Последующие части таблицы после слов
«Продолжение таблицы…» с указанием только ее номера начинают со строки с
нумерацией граф (рисунок 2.3).

==== 2.6.5

Заголовки граф рекомендуется записывать параллельно строкам таблицы. При
необходимости допускается перпендикулярное расположение заголовков граф (см.
рисунок 2.3). Заголовки граф и строки боковика таблицы следует писать с
прописной буквы, подзаголовки – со строчной (если только они не имеют
самостоятельного значения). Все заголовки, названия и подзаголовки указывают в
именительном падеже единственного числа, кроме случаев, когда в словосочетании
существительное в данном значении в единственном числе не употребляется. Слова в
таблице следует писать полностью без сокращений, за исключением отдельных
понятий, которые можно заменять буквенными обозначениями, установленными
стандартом ГОСТ 2.321–84 или другими принятыми обозначениями, если они пояснены
в тексте или приведены на иллюстрациях. Точка в конце заголовка не ставится.
Запрещается размещать в ячейке головки два заголовка, разделенные косой линией,
один из которых относится к боковику, а второй объединяет заголовки всех граф.
Графу «Номер по порядку» в таблицу включать не допускается. При необходимости
нумерации показателей порядковые номера указывают в первой графе через пробел
перед их наименованием (см. рисунок 2.4).

==== 2.6.6

В графе или строке боковика обозначения единиц физических величин приводят после
наименования показателя, отделяя их запятой (см. рисунок 2.4). Допускается
включать в таблицу графу «Обозначение единицы физической величины», если большая
часть наименований в боковике сопровождается размерностями.

==== 2.6.7

Если необходимы небольшие по объему пояснения к большей части строк таблицы, то
такие пояснения оформляют отдельной графой «Примечание» в соответствии с
рисунком 2.2. Если необходимо пояснить данные отдельных строк или граф, то
примечание оформляют отдельной строкой в конце таблицы над линией, обозначающей
окончание таблицы, в соответствии с рисунком 2.4.

==== 2.6.8

Таблицу с небольшим количеством граф допускается делить на части и помещать их
рядом на одной странице, разделяя двойной линией или линией удвоенной толщины,
при этом головку таблицы повторяют в каждой части (рисунок 2.5).

==== 2.6.9

При заполнении таблиц рекомендуется, чтобы число знаков после запятой было
одинаковым для каждого столбца цифр в соответствии с точностью измерительных
средств и инженерных расчетов. Числовые значения одной физической величины
необходимо располагать так, чтобы разряды чисел по всей графе находились один
под другим (см. рисунок 2.5). Числовые значения различных физических величин
располагают посередине ячейки в соответствии с рисунком 2.4. При указании в
строке боковика таблицы последовательных интервалов следует писать «От… до…
включ.», «Св… до… включ.». При отсутствии отдельных данных в таблице следует
ставить тире. Не допускается оставлять в графах таблиц пустые места.

==== 2.6.10

Пояснительная записка должна содержать краткие пояснения, относящиеся к таблице
в целом, а при необходимости и к ее отдельным частям. В пояснениях должны быть
сформулированы основные выводы, к которым приводят данные таблицы, или обращено
внимание на самое характерное или важное в ней.

==== 2.6.11

При наличии в дипломном проекте небольшого по объему цифрового материала его
нецелесообразно оформлять в виде таблицы, а следует давать текстом, располагая
данные в виде колонок.

=== 2.7 Оформление приложений

==== 2.7.1

В приложения пояснительной записки рекомендуется выносить информацию, имеющую
справочное или второстепенное значение, но необходимую для более полного
освещения темы проекта, или помещать отдельные ма-териалы (распечатки программ и
т. п.) для удобства работы с текстом пояснительной записки. Приложениями могут
быть математические формулы, номограммы, вспомогательные вычисления и расчеты,
описания алгоритмов и программ, технические характеристики различных устройств,
спецификации и т. п. Допускается использовать в качестве приложений отдельно
изданные конструкторские документы. Все приложения включают в общую нумерацию
страниц.

==== 2.7.2

В тексте пояснительной записки на все приложения должны быть ссылки. Приложения
располагают в порядке ссылок на них в тексте. Приложения обозначают заглавными
буквами русского алфавита, начиная с А, за исключением букв Ё, З, Й, О, Ч, Ъ, Ы,
Ь. Если в пояснительной записке одно приложение, оно также должно быть
обозначено ПРИЛОЖЕНИЕ А.

==== 2.7.3

Каждое приложение начинают с новой страницы. Вверху по центру страницы пишут
слово ПРИЛОЖЕНИЕ прописными буквами и его буквенное обозначение. Ниже в круглых
скобках строчными буквами указывают слово «обязательное», «рекомендуемое» или
«справочное». Еще ниже по центру размещают заголовок, который записывают с
прописной буквы. Иногда после заголовка делают обратную ссылку к основному
тексту пояснительной записки. Пример оформления приложения приведен в приложении
П.

=== 2.8 Оформление библиографического указателя СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ

==== 2.8.1

Ссылки на литературу, нормативно-техническую и другую документацию, иные
источники, использованные при работе над дипломным проектом (работой), помещают
в конце пояснительной записки перед приложениями в виде перечня СПИСОК
ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ, название которого записывают прописными буквами с
новой страницы по центру.

==== 2.8.2

В тексте пояснительной записки все ссылки на источники записывают арабскими
цифрами в квадратных скобках в возрастающем порядке. Должны быть приведены
ссылки на все без исключения источники, включенные в СПИСОК ИСПОЛЬЗОВАННЫХ
ИСТОЧНИКОВ.

==== 2.8.3

В СПИСКЕ ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ позиции располагают и нумеруют в той
последовательности, в которой расположены и пронумерованы ссылки в тексте
пояснительной записки.

==== 2.8.4

Без ссылок в тексте пояснительной записки разрешается использовать сведения,
полученные на лекциях, семинарских, практических и лабораторных занятиях. Однако
использованные учебные, учебно-методические материалы и пособия должны быть
приведены и расположены в конце СПИСКА ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ.

==== 2.8.5

Библиографические описания в СПИСКЕ ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ должны быть
выполнены в соответствии с правилами, установленными стандартом ГОСТ 7.1–2003.

==== 2.8.6

Примечания

* В списке запятая разделяет фамилию и инициалы.
* Инициалы разделяют пробелом.
* Вид издания (учеб. пособие; метод. указания и т. п.) указывается со строчной
  буквы.
* Библиографические знаки (: ; – /) с двух сторон отделяются пробелами.
* Место издания – Минск – следует писать полностью.
* Не допускаются ссылки на системы подсказок (help), а также сайт «Википедия» и
  другие аналогичные источники.

=== 2.9 Сноски, примечания и примеры

==== 2.9.1

Знаки сноски выполняют арабскими цифрами со скобкой и помещают справа на уровне
верхнего обреза слова, числа, символа, предложения, к которому дается пояснение
(см. приложение Л).

==== 2.9.2

Этот же знак повторяют внизу страницы под короткой чертой перед текстом
пояснения (см. приложение Л) с абзацного отступа.

==== 2.9.3

Примечания размещают после текстового, графического или табличного материала, к
которым они относятся. Слово «Примечание» пишется с прописной буквы с абзаца.
Если примечание одно, то после слова «Примечание» ставится тире и размещается
текст пояснения, начиная с прописной буквы (см. приложение Л). Если примечаний
несколько, то производится нумерация по порядку арабскими цифрами. Примечание к
таблице помещают в конце таблицы над нижней ограничивающей чертой (см. рисунок
2.4).

== 3 ТРЕБОВАНИЯ К ОФОРМЛЕНИЮ ГРАФИЧЕСКОГО МАТЕРИАЛА

=== 3.1 Общие требования

==== 3.1.1

Графическая часть дипломного проекта выполняется и оформляется или только с
использованием графических устройств вывода ПЭВМ, или только рукописным способом
на листах чертежной бумаги формата A1. Общий объем графической части указывается
в техническом задании (см. приложение Б). При ручном способе любой вид
графического изображения (чертеж, схема, диаграмма, график и т. д.) должен
выполняться чертежными инструментами (циркулем, лекалом, линейкой и т. п.)
черной тушью либо простым конструк- торским карандашом средней твердости. Причем
все линии изображений, все надписи должны иметь одинаковую интенсивность по
цвету.

==== 3.1.2

Графический материал одного вида, для выполнения которого необходим формат,
превышающий формат A1, размещается на нескольких листах формата A1. Для
графических материалов, имеющих самостоятельный характер и требующих меньшего
формата, чем A1, разрешается выбирать форматы A2, A3, A4 и размещать на общем
листе формата A1. Графический материал одного вида должен иметь рамку и основную
надпись. Его форматы, масштабы и правила выполнения должны соответствовать
требованиям ЕСКД. На чертежах и схемах должны быть представлены все необходимые
данные для однозначной передачи информации: условные графические обозначения
элементов, их буквенно-цифровые позиционные обозначения, символы физических
параметров в характерных точках схемы, цепи питания, квалифицирующие символы
рода тока и напряжения, поясняющие надписи и примечания. Данные об элементах и
устройствах должны быть указаны в перечнях, которые оформляются в виде отдельных
документов спецификации и помешаются в пояснительную записку перед ведомостью
документов (см. приложение Г). Элементы, устройства, составные части технической
системы на схемах изображаются в виде условных графических обозначений,
установленных государственными стандартами ЕСКД, а их наименования и номера
позиций должны соответствовать буквенным или буквенно-цифровым обозначениям по
ГОСТ 2.701-2008.

==== 3.1.3

Листы основных форматов A1, A2 и A3, имеющие рамки и основную надпись, можно
располагать горизонтально и вертикально. Листы формата А4 размером 210 на 297
мм располагаются только вертикально, а основные надписи -- внизу листа. Формат
листа и его расположение выбирают в зависимости от вида графического материала,
его объема, сложности и необходимости обеспечить на всех листах графической
части дипломного проекта единообразие выполнения условных графических и
позиционных обозначений, линий связи и стрелок. Формат А4 используют, как
правило, для оформления текстовых документов, например, ведомости, документов,
спецификаций и др. Рамки наносят сплошной основной линией на расстоянии 5 мм от
границы формата сверху, справа и снизу. Слева оставляют поле шириной 20 мм.

==== 3.1.4

На листах форматов A1, A2 и A3 основную надпись располагают в правом нижнем углу
конструкторских документов. На листах формата A4 основную надпись располагают
только вдоль короткой стороны листа. На документах, выполняемых в соответствии с
ГОСТ 2.605-68 «ЕСКД. Плакаты учебно-технические. Общие технические требования»,
основная надпись помещается на оборотной стороне документа. Разновидности
основной надписи для графических и текстовых документов приведены на рисунке
3.1. В круглых скобках на основных надписях обозначен номер графы, каждую из
которых заполняют в соответствии с требованиями стандартов ЕСКД. В графе 1
указывают наименование изделия и наименование документа, если этому документу
присвоен код. Наименование изделия записывают в именительном падеже
единственного числа. Оно должно соответствовать принятой терминологии и быть по
возможности кратким. В наименовании, состоящем из нескольких слов, на первом
месте помещают имя существительное, например «Измеритель универсальный». Если
документу присвоен код в соответствии с ГОСТ 2.102-68, 2.601-2006, 2.602-95 и
2.701-2008, то кроме наименования изделия в графе 1 указывают и наименование
документа. В графе 2 указывают обозначение документа по ГОСТ 2.201-80. Структура
обозначения документа в основной надписи имеет вид XXXX.XXXXXXX.XXX

* Порядковый номер документа (от 001 до 999)
* Код классификационной характеристики (выбирается по Классификатору ЕСКД)
* Код организации-разработчика состоит из четырех букв (для дипломных проектов,
  выполняемых в БГУИР - ГУИР)

Код классификационной характеристики состоит из шести знаков (класс -- два
знака; подкласс, группа, подгруппа и вид -- по одному знаку) и записывается
арабскими цифрами. Структура кода имеет вид -- XX X X X X

* Класс изделия
* Подкласс
* Группа
* Подгруппа
* Вид изделия

Код классификационной характеристики изделия выбирают по Классификатору ЕСКД
(ГОСТ 2.201-80). Если документ относится к основному конструкторскому документу
(чертеж детали или спецификация), то его обозначение имеет следующий вид:
ГУИР.XXXXXX.001. Для неосновных конструкторских документов к выбранному по
описанной методике обозначению документа добавляют его код, который определяется
стандартами ГОСТ 2.102-68, ГОСТ 2.601-2006, ГОСТ 2.602-95 и ГОСТ 2.701-2008. Код
документа может состоять не более чем из четырех знаков (букв или букв и цифр).
Например, для схемы электрической принципиальной обозначение документа включает
код Э3 и имеет вид ГУИР.XXXXXX.001Э3, для перечня к схеме электрической
принципиальной – код ПЭ3 и т. д. В графе 3 основной надписи записывают принятое
обозначение материала, из которого изготавливают деталь. Эту графу заполняют
только на чертежах деталей. В графе 4 указывают литеру, присвоенную данному
документу. Графу заполняют последовательно, начиная с крайней левой клетки.
Литера определяется стадией или этапом разработки конструкторской документации.
Так, на стадии эскизного проектирования документации присваивается литера «Э»,
на стадии технического проектирования – литера «Т», документации единичного
производства – литера «И» и т. д. В дипломных проектах (работах), как правило,
используется литера «Т». В графе 5 указывают массу изделия в соответствии с ГОСТ
2.109-73. Масштаб изображения выбирают в соответствии с ГОСТ 2.302-68 и про-
ставляют в графе 6. Указанный стандарт не распространяется на чертежи схем. В
графе 7 приводят порядковый номер листа конструкторского документа. Если
документ состоит из одного листа, то данную графу не заполняют. В графе 8
указывают общее количество листов документа. Эта графа заполняется только на
первом листе документа. В графе 9 приводят сокращенное название выпускающей
кафедры, на которой выполняется дипломный проект, например ПИКС (кафедра
проектирования информационно-компьютерных систем), и номер учебной группы
студента (разработчика документа). В графе 10 указывают характер работы,
выполняемой лицом, подписывающим документ; в графе 11 -- фамилию этого лица; в
графе 12 -- его подпись и в графе 13 -- дату подписания документа. Свободную
строку для дипломных проектов (работ) заполняет рецензент. Далее указывают
фамилию рецензента дипломного проекта (работы), затем следует его подпись и
проставляется дата подписания документа.

==== 3.1.5

Схемы являются основным графическим материалом дипломного проекта. Их
наименования и обозначения должны соответствовать стандартам ЕСКД. В ГОСТ
2.701-2008 установлены классификация и обозначение схем. По важности основного
вида элементов и связей между ними схемы подразделяются на следующие виды,
обозначаемые буквами: Э -- электрические, Г -- гидравлические, П --
пневматические, X -- газовые, К -- кинематические, В -- вакуумные, Л --
оптические, Р -- энергетические, С -- комбинированные, Е -- деления. По
основному назначению схемы подразделяются на типы, обозначаемые цифрами: 1 --
структурные, 2 -- функциональные, 3 -- принципиальные (полные), 4 -- соединений
(монтажные), 5 -- подключения, 6 -- общие, 7 -- расположения, 0 -- объединенные.
Наименование схемы определяется ее видом и типом, например, схема электрическая
функциональная. Схемы обозначают буквенно-цифровым кодом, например: Э1 -- схема
электрическая структурная, К2 -- схема кинематическая функциональная. Если
разрабатывается несколько схем одного вида и типа, причем каждая схема в форме
самостоятельного документа, то в наименованиях каждой схемы указывают ее
функциональную особенность. В этом случае, начиная со второй схемы, к коду схемы
в обозначении добавляют через точку порядковый номер. В ГОСТ 19.701-90
установлены следующие схемы алгоритмов, программ, данных и систем: схема данных,
схема программы, схема работы системы, схема взаимодействия программ, схема
ресурсов системы и т. д. Для всех схем, относящихся к проектированию
информационных систем (схемы алгоритмов, программ, баз данных и т. д.),
рекомендуется использовать код ПД.

==== 3.1.6

Чертежи разрабатываются с целью декомпозиции и пояснения сложных задач
проектирования (условий их решения и осуществления). Наименования и обозначения
чертежей должны соответствовать стандартам, установленным ГОСТ 2.102-68. В
дипломном проекте при необходимости могут разрабатываться следующие виды
чертежей, обозначаемые двухбуквенным кодом: ВО -- чертеж общего вида,
определяющий конструкцию изделия, взаимодействие его составных частей и
поясняющий принцип работы; ТЧ -- теоретический чертеж, определяющий
геометрическую форму изделия, координаты составных частей и поясняющий характер
движения этих частей относительно заданной системы координат; МЭ --
электромонтажный чертеж, содержащий данные, необходимые для выполнения
электрического монтажа.

==== 3.1.7

Диаграммы, графики различного назначения, циклограммы, таблицы и другие виды
информационного изображения фактического материала представляются в виде
самостоятельных документов в тех случаях, когда необходимо пояснить проведенные
расчеты, обосновать принятые схемотехнические решения, повысить их
достоверность. Согласно ГОСТ 2.102-68 таблицам присваивается двухбуквенный код
ТБ, расчетам -- РР. Код можно присваивать и другим документам. В графе 1
углового штампа записывается наименование документа. Наименование должно быть
кратким и отражать информационную суть изображения. Например, РР -- диаграммы
адресного обмена по магистрали микропроцессорных средств производственной
системы в графе 1 записываются «Диаграммы адресного обмена».

==== 3.1.8

Ведомости спецификации для электрических схем присваивается двухбуквенный код --
ПЭ3.

==== 3.1.9

Любой вид графического материала в дипломном проекте (работе) должен иметь
высокую степень самостоятельности, а содержащаяся в нем информация должна быть
ясной и однозначной. Поэтому при изображении чертежей, схем, диаграмм, графиков
необходимо использовать установленные государственными стандартами условные
графические, буквенные, буквенно-цифровые и цифровые позиционные обозначения,
строго соблюдать правила выполнения и оформления графического материала.

==== 3.1.10

Графический материал для дипломных работ выполняется в виде плакатов. Требования
к выполнению плакатов изложены в подразделе 3.19 настоящего стандарта.

==== 3.1.11

При осуществлении чертежных работ с помощью графических устройств вывода ПЭВМ
допускается выполнение чертежей, схем и плакатов в цвете по согласованию с
руководителем и консультантом от кафедры.
